spring:
  application:
    name: admin-panel
  datasource:
    url: jdbc:postgresql://192.168.19.82:5438/postgres
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update


server:
  port: 0

app:
  comments-and-votes-mode: all

management:
  endpoints:
    web:
      ecposure:
        include=*:

