spring:
  application:
    name: admin-panel
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update


server:
  port: 0

api:
  capabilities:
    adminControlSwitch=true:
