spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/admindb
    username: postgres
    password: Aa123456
  jpa:
    hibernate:
      ddl-auto: update


server:
  port: 8282

api:
  capabilities:
    adminControlSwitch=false: